#!/usr/bin/env python
# coding: utf-8

import pickle
from stats_utils import *
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import wilcoxon


def main():

    print ("CBOW")
    
    with open('/home/fgazzavi/f_env/Thai/CBOW/Thai_Gabriel_Graph_sample1%_CBOW_1gram_6_ig.pkl', 'rb') as inp:
        graph = pickle.load(inp)

    weights = []
    for e in graph.es:
        weights.append(e['weight'])
    print (max(weights))
    diameter = max(weights) +1
    limit = 500
    human, bot = return_Arrays_of_path_length_withNFAndLimit( "/home/fgazzavi/f_env/Thai/CBOW/test_original_corpus_CBOW.txt", "/home/fgazzavi/f_env/Thai/CBOW/test_bot_corpus_CBOW.txt",graph,diameter,limit)
    X = np.arange(0,len(human))
    plt.plot(X, human, color='r', label='human')
    plt.plot(X, bot, color='g', label='bot')
    plt.xlabel("text number")
    plt.ylabel("Weighted Path length")
    plt.title("Weighted path length for texts generated by humans and bots")
    plt.legend()
    plt.savefig('/home/fgazzavi/f_env/Thai/CBOW/Thai_Weighted_path_length_CBOW_500.pdf')
    #plt.show()
    plt.clf()

    with open('/home/fgazzavi/f_env/Thai/CBOW/wilcoxon_CBOW.txt', 'a',encoding='utf-8') as f:
        f.write(f"Wilcoxon Signed-Rank Test for human and bots samples (Path length)\n")
        stat, p = wilcoxon(human, bot)
        f.write('Statistics=%.3f, p=%.3f \n' % (stat, p))
        alpha = 0.05
        if p > alpha:
            f.write(f"Same distribution (fail to reject H0)\n")
        else:
            f.write(f"Different distribution (reject H0)\n")


    with open('/home/fgazzavi/f_env/Thai/CBOW/Thai_CCW_CBOW_1gram_6_ig.pkl', 'rb') as outp:
        cc_dic = pickle.load(outp)
    human , bot = return_Arrys_of_centralites( "/home/fgazzavi/f_env/Thai/CBOW/test_original_corpus_CBOW.txt", "/home/fgazzavi/f_env/Thai/CBOW/test_bot_corpus_CBOW.txt",graph,cc_dic,limit)
    X = np.arange(0,len(human))
    plt.plot(X, human, color='r', label='human')
    plt.plot(X, bot, color='g', label='bot')
    plt.xlabel("text number")
    plt.ylabel("Weighted closness centrality")
    plt.title("Weighted closness Centrality for texts generated by humans and bots")
    plt.legend()
    plt.savefig('/home/fgazzavi/f_env/Thai/CBOW/Thai_Weighted_cc_CBOW_500.pdf')
    plt.clf()

    with open('/home/fgazzavi/f_env/Thai/CBOW/wilcoxon_CBOW.txt', 'a',encoding='utf-8') as f:
        f.write(f"Wilcoxon Signed-Rank Test for human and bots samples (Closness centrality)\n")
        stat, p = wilcoxon(human, bot)
        f.write('Statistics=%.3f, p=%.3f \n' % (stat, p))
        alpha = 0.05
        if p > alpha:
            f.write(f"Same distribution (fail to reject H0)\n")
        else:
            f.write(f"Different distribution (reject H0)\n")

    with open('/home/fgazzavi/f_env/Thai/CBOW/Thai_BCW_CBOW_1gram_6_ig.pkl', 'rb') as outp:
        bc_dic = pickle.load(outp)
    human , bot = return_Arrys_of_centralites("/home/fgazzavi/f_env/Thai/CBOW/test_original_corpus_CBOW.txt", "/home/fgazzavi/f_env/Thai/CBOW/test_bot_corpus_CBOW.txt",graph,bc_dic,limit)
    X = np.arange(0,len(human))
    plt.plot(X, human, color='r', label='human')
    plt.plot(X, bot, color='g', label='bot')
    plt.xlabel("text number")
    plt.ylabel("Weighted betweeness centrality")
    plt.title("Weighted betweeness centrality for texts generated by humans and bots")
    plt.legend()
    plt.savefig('/home/fgazzavi/f_env/Thai/CBOW/Thai_Weighted_bc_CBOW_500.pdf')
    plt.clf()

    with open('/home/fgazzavi/f_env/Thai/CBOW/wilcoxon_CBOW.txt', 'a',encoding='utf-8') as f:
        f.write(f"Wilcoxon Signed-Rank Test for human and bots samples (Betweeness centrality)\n")
        stat, p = wilcoxon(human, bot)
        f.write('Statistics=%.3f, p=%.3f \n' % (stat, p))
        alpha = 0.05
        if p > alpha:
            f.write(f"Same distribution (fail to reject H0)\n")
        else:
            f.write(f"Different distribution (reject H0)\n")
   
if __name__ == "__main__":

    main()



